server:
  servlet:
    context-path: /
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.1.54:3306/security_demo?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # com.mysql.jdbc.Driver Spring Boot 2.1.0 之前用这个  com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

logging:
  path: D:\logs\Spring-Security\spring-security-demo
